package cn.itcast.domain.cargo;

import cn.itcast.domain.BaseEntity;

import java.util.Date;

/**
 * 工厂类
 *
 * @author cbh
 */
public class Factory extends BaseEntity {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column co_factory.id
	 *
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	private String id;

	/**
	 * 厂家类型：货物/附件
	 */
	private String ctype;

	/**
	 * 厂家全称
	 */
	private String fullName;

	/**
	 * 厂家简称
	 */
	private String factoryName;

	/**
	 * 联系人
	 */
	private String contacts;

	/**
	 * 电话
	 */
	private String phone;

	/**
	 * 手机
	 */
	private String mobile;

	/**
	 * 传真
	 */
	private String fax;

	/**
	 * 地址
	 */
	private String address;

	/**
	 * 验货员
	 */
	private String inspector;

	/**
	 * 说明
	 */
	private String remark;

	/**
	 * 排序号
	 */
	private Long orderNo;

	/**
	 * 状态
	 */
	private String state;

	public Factory() {
	}

	public Factory(String id, String ctype, String fullName, String factoryName, String contacts, String phone, String mobile, String fax, String address, String inspector, String remark, Long orderNo, String state) {
		this.id = id;
		this.ctype = ctype;
		this.fullName = fullName;
		this.factoryName = factoryName;
		this.contacts = contacts;
		this.phone = phone;
		this.mobile = mobile;
		this.fax = fax;
		this.address = address;
		this.inspector = inspector;
		this.remark = remark;
		this.orderNo = orderNo;
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column co_factory.id
	 *
	 * @return the value of co_factory.id
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column co_factory.id
	 *
	 * @param id the value for co_factory.id
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column co_factory.ctype
	 *
	 * @return the value of co_factory.ctype
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public String getCtype() {
		return ctype;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column co_factory.ctype
	 *
	 * @param ctype the value for co_factory.ctype
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public void setCtype(String ctype) {
		this.ctype = ctype == null ? null : ctype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column co_factory.full_name
	 *
	 * @return the value of co_factory.full_name
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public String getFullName() {
		return fullName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column co_factory.full_name
	 *
	 * @param fullName the value for co_factory.full_name
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public void setFullName(String fullName) {
		this.fullName = fullName == null ? null : fullName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column co_factory.factory_name
	 *
	 * @return the value of co_factory.factory_name
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public String getFactoryName() {
		return factoryName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column co_factory.factory_name
	 *
	 * @param factoryName the value for co_factory.factory_name
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public void setFactoryName(String factoryName) {
		this.factoryName = factoryName == null ? null : factoryName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column co_factory.contacts
	 *
	 * @return the value of co_factory.contacts
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public String getContacts() {
		return contacts;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column co_factory.contacts
	 *
	 * @param contacts the value for co_factory.contacts
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public void setContacts(String contacts) {
		this.contacts = contacts == null ? null : contacts.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column co_factory.phone
	 *
	 * @return the value of co_factory.phone
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column co_factory.phone
	 *
	 * @param phone the value for co_factory.phone
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column co_factory.mobile
	 *
	 * @return the value of co_factory.mobile
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column co_factory.mobile
	 *
	 * @param mobile the value for co_factory.mobile
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column co_factory.fax
	 *
	 * @return the value of co_factory.fax
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column co_factory.fax
	 *
	 * @param fax the value for co_factory.fax
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public void setFax(String fax) {
		this.fax = fax == null ? null : fax.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column co_factory.address
	 *
	 * @return the value of co_factory.address
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column co_factory.address
	 *
	 * @param address the value for co_factory.address
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column co_factory.inspector
	 *
	 * @return the value of co_factory.inspector
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public String getInspector() {
		return inspector;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column co_factory.inspector
	 *
	 * @param inspector the value for co_factory.inspector
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public void setInspector(String inspector) {
		this.inspector = inspector == null ? null : inspector.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column co_factory.remark
	 *
	 * @return the value of co_factory.remark
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column co_factory.remark
	 *
	 * @param remark the value for co_factory.remark
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column co_factory.order_no
	 *
	 * @return the value of co_factory.order_no
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public Long getOrderNo() {
		return orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column co_factory.order_no
	 *
	 * @param orderNo the value for co_factory.order_no
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public void setOrderNo(Long orderNo) {
		this.orderNo = orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column co_factory.stat
	 *
	 * @return the value of co_factory.stat
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column co_factory.stat
	 *
	 * @param state the value for co_factory.stat
	 * @mbg.generated Sun Dec 27 21:38:18 CST 2020
	 */
	public void setState(String state) {
		this.state = state == null ? null : state.trim();
	}

	public String toString() {
		return "Factory{id = " + id + ", ctype = " + ctype + ", fullName = " + fullName + ", factoryName = " + factoryName + ", contacts = " + contacts + ", phone = " + phone + ", mobile = " + mobile + ", fax = " + fax + ", address = " + address + ", inspector = " + inspector + ", remark = " + remark + ", orderNo = " + orderNo + ", stat = " + state + "}";
	}
}